name: Pull request
on: [pull_request]
jobs:
  PullRequests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envKey_POSTGRES_USER: "postgres"
          envKey_POSTGRES_PASSWORD: "postgres"
          envKey_POSTGRES_DB: "postgres"
          envKey_POSTGRES_DATABASE_URL: "postgresql://postgres:postgres@db:5432/students__tests"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml run node_app npm run test